[package]
name = "process_test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = ["Wdk_System_SystemInformation", "Win32_System_ProcessStatus", "Win32_System_WindowsProgramming"] }

[profile.release]
strip = true
